# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.checkout("AbstractTrees", "d2096ba3a3b23fd4f70e619cdf6810708a54e22d"); Pkg.build("Deprecations"); Pkg.test("Deprecations"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Deprecations")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
