# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); cd(Pkg.dir("CSTParser")) do; run(`git remote add mine https://github.com/Keno/CSTParser.jl.git`); run(`git fetch mine`); run(`git checkout mine/kf/newwhitespace`); end; Pkg.build("Deprecations"); Pkg.test("Deprecations"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Deprecations")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
